---
ignore_compute_resource_errors: true
satellite_repos: "{{ rhsm_repos }}"
satellite_verify_ssl: no
rhsm_verify_ssl: yes
manifest_download_dir: /root
local_manifest_path: /home/rheron/Downloads/manifest_Lunchbox_20200728T182341Z.zip

# Products releases
sat_tools: "{{ satellite_version }"


# setup satellite org, location with with products
satellite_orgs:
  - name: ACME2
    admin_username: "{{ satellite_user }}"
    admin_password: "{{ satellite_password }}"
    state: present
    sync_right_away: no
    redhat_manifest:
      name: sat6u8v2
      uuid: e7d1a9b1-fbc6-49bc-af5f-effe3b589437
      use_local_manifest: yes
      path: /root/satellite_manifest.zip
      state: present
      pool:
        - id: 8a85f99b70d0559c0171092c28b946b3
          state: present
          quantity: 1
        - id: 8a85f99b727637b201729a1f407f5f3b
          state: present
          quantity: 1
    locations:
      - name: Orlando
        state: present
    products:
      - rhel8
    lifecycle_environments:
      - name: Dev
        prior: Library
        state: present
      - name: QA
        prior: Dev
        state: present
      - name: Production
        prior: QA
        state: present
    sync_plans:
      - name: "Red Hat Sync Plan"
        date: "2019/06/16 00:00:00 +0000"
        interval: daily
        enabled: true
        description: "Sync Plan for Red Hat products"

