---
satellite_repos: "{{ rhsm_repos }}"
satellite_verify_ssl: no
rhsm_verify_ssl: yes
manifest_download_dir: /root
local_manifest_path: "{{ downloaded_manifest_file }}"
satellite_url: "https://{{ satellite_hostname }}"

# Products releases
sat_tools: "{{ satellite_version }"

# setup satellite org, location with with products
satellite_orgs:
  - name: "{{ satellite_default_organization }}"
    admin_username: "{{ satellite_user }}"
    admin_password: "{{ satellite_password }}"
    state: present
    sync_right_away: "{{ sync_now }}"
    redhat_manifest:
      name: "{{ manifest_name }}"
      uuid: "{{ manifest_uuid }}"
      use_local_manifest: "{{ create_manifest }}"
#      path: /root/satellite_manifest.zip
      state: present
      pool: "{{ pool_ids }}"
    locations:
      - name: "{{ satellite_default_location }}"
        state: present
    products: "{{ products_to_enable }}"
    lifecycle_environments: "{{ default_lcen }}"
    sync_plans:
      - name: "{{ sync_plan_name }}"
        date: "{{ sync_plan_date }}"
        interval: "{{  sync_interval }}"
        enabled: true
        description: "Default Sync Plan for Red Hat products"

