---

- name: datacenter_1-subnet-10.15.108.0_22
  network: 10.15.108.0
  mask: 255.255.255.0
  gateway: 10.15.108.254
  dns_primary: 10.15.108.148
  dns_secondary: 10.15.108.149
  ipam: None
  boot_mode: Static
  organizations:
    - name: "{{ satellite_org }}"
  locations:
    - name: "{{ satellite_location }}"
  domains:
    - name: "{{ domain }}"
