---

- name: configure satellite
  hosts:
    - sat

  vars_files:
    - vars/main.yml
    - vars/satellite.yml

  collections:
    - jjaswanson4.configure_satellite
    - redhat.satellite

  roles:
    - redhat-satellite-quickstart
    #- jjaswanson4.configure_satellite.configure_foreman
    #- jjaswanson4.configure_satellite.configure_katello
