---
- name: configure satellite
  gather_facts: no
  hosts:
    - sat

  vars_files:
    - vars/main.yml
    - vars/satellite.yml

  collections:
    - redhat.satellite

  roles:
    - redhat-satellite-quickstart
