---
- name: setup server to be satellite or a capsule
  hosts:
    - sat
#    - capsule
  become: true

  vars_files:
    - vars/main.yml
    - vars/rhel-sat-server.yml

  vars:
    system_registered: no

  pre_tasks:
    - name: check for RHEL7
      fail:
        msg: "Satellite 6 must be run on a RHEL7 host"
      when:
        - ansible_facts['distribution'] != 'RedHat' or
          ansible_facts['distribution_major_version'] | int != 7

    - name: check for x86_64 architecture
      fail:
        msg: "Satellite 6 requires x86_64 architecture"
      when:
        - ansible_facts['architecture'] != 'x86_64'

    - name: check cpu
      fail:
        msg: "Satellite requires at least 4 cpu cores"
      when:
        - ansible_facts['processor_count'] | int * ansible_facts['processor_count'] | int < 4

    - name: check memory
      fail:
        msg: "Satellite requires at least 20GB of ram"
      when:
        - ansible_facts['memory_mb']['real']['total'] | int < 20480

    - name: get current umask
      shell: umask
      register: current_umask
      changed_when: false
      check_mode: false

    - name: check umask
      fail:
        msg: "system umask must be 0022"
      when:
        - current_umask.stdout != '0022'

    - name: check upstream dns
      shell: ping -c 1 "{{ ansible_fqdn }}"
      register: dns_status
      check_mode: false
      failed_when: false
      changed_when: false

    - name: fail on dns
      fail:
        msg: "upstream dns must be configured"
      when:
        - dns_status.rc | int != 0

    - name: check registration status
      command: subscription-manager identity
      ignore_errors: yes
      register: subscription_status
      changed_when: false
      become: yes

    - name: set subscription status
      set_fact:
        system_registered: yes
      when: "'This system is not yet registered' not in subscription_status.stderr"

    - name: fail when system not registered and no registration information is provided
      fail:
        msg: "System is not registered. Edit playbooks/vars/main.yml with you registration info"
      when: not system_registered and (rhsm_activationkey is not defined or rhsm_user is not defined)

  tasks:
    - name: ensure system is registered to Red Hat
      include_role:
        name: swygue-redhat-subscription
      when: not system_registered or not is_repos_enabled

    - name: create satellite paritions
      include_role:
        name: swygue-lvm
      when: sat_vg_disk is defined and sat_vg_disk != ''
